COURSE_ACTS(COURSE_BOB, _(" 1 GREEN FIELD MEADOWS"), 	_("CLIMB TO THE MOUNTAIN TOP"), 	_("PUZZLE OF THE FLOWER FIELDS"), 	_("BOUNCE TO THE HIGH PEAK"), 	_("8 BLUE COINS OF THE MEADOWS"), 	_("THE FLOWER AREA'S LOST STAR"), 	_("GUARDED BY THE CHAIN CHOMPS"))

COURSE_ACTS(COURSE_WF, _(" 2 AQUA CHAMBER"), 	_("TOP OF THE LIGHTHOUSE"), 	_("THE SUNKEN CASTLE'S TREASURE"), 	_("THE AQUA-SIDE FLIP SWITCHES"), 	_("THE SECRET PASSAGE"), 	_("BLUE COINS OF THE CHAMBER"), 	_("KING WHOMP'S TOWER RUMBLE"))

COURSE_ACTS(COURSE_JRB, _(" 3 ASTEROID BASE"), 	_("THE BASE HEADQUARTERS"), 	_("THE OBSERVATION TOWER"), 	_("FLIP-SWITCHES OF THE BASE"), 	_("THE HIGH HIGH TOWER"), 	_("STORM THE BASE FOR BLUE COINS"), 	_("HIDDEN WITHIN THE BASE"))

COURSE_ACTS(COURSE_CCM, _(" 4 SNOW-BURN LAND"), 	_("THE SNOWY SUMMIT"), 	_("THE ICED LAVA CAVERN"), 	_("THE LAVA-BURNT TOWER"), 	_("BLUE COINS THROUGH HOT AND COLD"), 	_("THE SECRET SHELL RIDE"), 	_("CHILL BULLY'S ICED LAVA BATTLE"))

COURSE_ACTS(COURSE_BBH, _(" 5 THE LOST GALAXY"), 	_("THE ANCIENT SLAB"), 	_("THE LOST KINGDOM"), 	_("TOP OF THE MOUNTAIN"), 	_("THE LOST BLUE COINS"), 	_("THE MEGA SLIDE"), 	_("FIND THE SWITCH"))

COURSE_ACTS(COURSE_HMC, _(" 6 SKY TEMPLE LANDS"), 	_("TOP OF THE SKY TOWER"), 	_("THE SKY-HIGH FLOATING BRIDGE"), 	_("DIAMONDS IN THE SKY"), 	_("SKY-HIGH SKY COINS"), 	_("THE DREADFUL TOWER"), 	_("SECRET OF THE BIG TREE"))

COURSE_ACTS(COURSE_LLL, _(" 7 THE ANCIENT KINGDOM"), 	_("TOP OF THE ANCIENT TOWER"), 	_("THE GREAT LABYRINTH"), 	_("THE QUICK SAND SEA"), 	_("COINS OF THE ANCIENT VALLEY"), 	_("IN THE CLUTCHES OF KLEPTO"), 	_("GUARDIANS OF THE ANCIENT TEMPLE"))

COURSE_ACTS(COURSE_SSL, _(" 8 GHOSTLY CASTLE FIELDS"), 	_("TOP OF THE DEFENSE TOWER"), 	_("THE CAGED STAR"), 	_("TREASURE OF THE WEAPON STORAGE HUT"), 	_("THE GHOSTLY COINS"), 	_("SECRET WARP TO THE TOWER"), 	_("THE HAUNTED CASTLE"))

COURSE_ACTS(COURSE_DDD, _(" 9 THE SPACE CAVES"), 	_("DOWN THE DEADLY SPIRAL"), 	_("BLOCKS OF THE DEEP CAVES"), 	_("THE PERILOUS CAVE CLIMB"), 	_("CAVE EXPLORING FOR BLUE COINS"), 	_("THE SECRET CAVE"), 	_("THE CAVE BASE TOWER"))

COURSE_ACTS(COURSE_SL, _("10 TWIN MOUNTAINS"), 	_("SHINING DOWN FROM THE TWIN PEAKS"), 	_("ACROSS THE CLIFFS OF DANGER"), 	_("VANISH INTO THE CAGE"), 	_("THE MOUNTAINOUS COINS"), 	_("THE WINDMILL'S SECRET"), 	_("THE SWITCH AND THE RIVER"))

COURSE_ACTS(COURSE_WDW, _("11 MOLTEN LAVA BARRIER"), 	_("TOP OF THE VOLCANO"), 	_("CENTRAL TOP OF THE BARRIER"), 	_("METAL-BURN THROUGH THE LAVA TOWER"), 	_("THE PILLARS OF PERIL"), 	_("FLIP-SWITCH, FLIP-BURN"), 	_("BIG BULLY'S TOWER OF RAGE"))

COURSE_ACTS(COURSE_TTM, _("12 MYSTIC TEMPLE BAY"), 	_("THE HIGHEST ISLAND"), 	_("GET INTO THE CASTLE"), 	_("THE LOST TEMPLE TOWER"), 	_("COINS OF THE ANCIENT TEMPLE BAY"), 	_("DRAINING OUT THE WATER"), 	_("THE SECRET OF MYSTIC TEMPLE BAY"))

COURSE_ACTS(COURSE_THI, _("13 DEATH MOUNTAIN FIELDS"), 	_("ACROSS THE BRIDGES OF PERIL"), 	_("INSIDE THE DEATH MOUNTAIN"), 	_("SWITCHES OF THE DEADLY PIT"), 	_("COINS OF THE VALLEY"), 	_("RIDE ACROSS THE TOXIC MATTER"), 	_("SECRET OF THE MONTY MOLE"))

COURSE_ACTS(COURSE_TTC, _("14 GALACTIC SPACE BASE"), 	_("IN THE LIGHT OF THE BEACON"), 	_("THE OBSERVATORY TOWER"), 	_("SHUT DOWN THE COMPUTERS"), 	_("STORMING THE BASE FOR BLUE COINS"), 	_("THE CONTROL TOWER"), 	_("SPIKO-LAKITU RETURNS"))

COURSE_ACTS(COURSE_RR, _("15 STAR GLITTER SKY-ISLES"), 	_("ACROSS THE STAR GLITTER PATH"), 	_("THE STARRY SKY'S TOWER"), 	_("RAINBOW STARS IN THE SKY"), 	_("GLITTERING COINS OF THE STARS"), 	_("SECRET OF THE RAINBOW ROAD"), 	_("SWITCHES OF THE GLITTERING FIELDS"))

SECRET_STAR(15, _("   BOILING LAVA TOWERS"))
SECRET_STAR(16, _("   THE AQUATIC CASTLE"))
SECRET_STAR(17, _("   INTER-GALACTIC BATTLEFORT"))
SECRET_STAR(18, _("   WATER TEMPLE"))
SECRET_STAR(19, _("   GALACTIC PLAINS"))
SECRET_STAR(20, _("   THE GALACTIC ALTAR"))
SECRET_STAR(21, _("   FLIP-SWITCH FORTRESS"))
SECRET_STAR(22, _("   KING STARSTONE'S GALACTIC SHOWDOWN"))
SECRET_STAR(23, _("   THE SECRET ROOM"))
SECRET_STAR(24, _(""))
CASTLE_SECRET_STARS(_("   HIDDEN STARS"))
EXTRA_TEXT(0,_("A SILVER STAR!"))
EXTRA_TEXT(1,_(""))
EXTRA_TEXT(2,_(""))
EXTRA_TEXT(3,_(""))
EXTRA_TEXT(4,_(""))
EXTRA_TEXT(5,_(""))
EXTRA_TEXT(6,_(""))
